server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food_delivery
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET}
  expiryMinutes: 60

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false

application:
  bucket:
    name: ${AWS_BUCKET}

