version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: food_delivery_postgres
    restart: always
    environment:
      POSTGRES_USER: vamsi
      POSTGRES_PASSWORD: vamsi
      POSTGRES_DB: food_delivery
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
